replicaCount: 1

image:
  repository: svcosti/cidrapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: snevs.github.io
      paths:
        - /
        
resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
  annotations: {}
  automountServiceAccountToken: true
  automount: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

